services:
  gundeals-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DOMAIN=localhost:8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s